Revert "Add `@[simps]` to `reindex`"
This reverts commit 13559f78727f2dcec94b36a6290e0f620e8e93ad.

The `@[simps]` attribute generates `reindex_symm_step` etc. which conflict with the manually defined `reindex_symm`.

/- The `simpNF` linter reports:
SOME SIMP LEMMAS ARE NOT IN SIMP-NORMAL FORM.
see note [simp-normal form] for tips how to debug this.
https://leanprover-community.github.io/mathlib_docs/notes.html#simp-normal%20form -/
-- Mathlib.Computability.DFA
Error: ./././Mathlib/Computability/DFA.lean:219:3: error: DFA.reindex_symm_apply_step.{u_1, u, v} simp can prove this:
  by simp only [@DFA.reindex_symm, @DFA.reindex_apply_step, @Equiv.symm_symm]
One of the lemmas above could be a duplicate.
If that's not the case try reordering lemmas or adding @[priority].

Error: ./././Mathlib/Computability/DFA.lean:219:3: error: DFA.reindex_symm_apply_accept.{u_1, u, v} simp can prove this:
  by simp only [@DFA.reindex_symm, @DFA.reindex_apply_accept, @Equiv.symm_symm]
One of the lemmas above could be a duplicate.
If that's not the case try reordering lemmas or adding @[priority].